### ISSUE TITLE
Accessing page's content not as a component

### ISSUE THREAD

**Issue by asaf** [TorstenDittmann/svelte-markdoc-preprocess#12] opened 2023-09-06 08:41 UTC
Hey,
Nice work!

I'd like to calculate the _reading time_ of a markdown page, for this I need access to the markdown content,

What would be the appropriate way to read the markdown content? currently using ` await import(`../${params.slug}.markdoc`);` as stated in the [slug](https://github.com/TorstenDittmann/svelte-markdoc-preprocess/blob/main/apps/demo/src/routes/playground/glob/%5Bslug%5D/%2Bpage.ts) example produces `.default` which is a component and access to the frontmatter but not the content itself.

Thanks,
Asaf.

**Comment by TorstenDittmann** [comment] 2023-09-06 08:53
Hey 👋🏻 

You can call the `render()` function on the components `default`, which will return an object containing the `html`, `css` and `head`. If you now strip the `html` of the HTML tags itself, you are left with only the text.

`import.default.render()` returns something like this:
```json
{
   "html":"<article><h1>Hello World</h1></article>",
   "css":{
      "code":"",
      "map":null
   },
   "head":""
}
```

You could also import the component in its raw Markdoc form, doing `import('../slug.markdoc?raw');`.

**Comment by asaf** [comment] 2023-09-06 09:06
Hey,

Invoking `import.default.render()` on the `+page.ts` causes `TypeError: article.default.render is not a function`
It looks like the `load` function is invoked twice, one in the backend and one time on the frontend (not sure why), in the second time the render function does not exist.

**Comment by TorstenDittmann** [comment] 2023-09-06 09:43
Running into the same issue 🤔 Not sure why it happens, must be a svelte thing.

My first thought would be to try an additional `?raw` import and use the raw markdown for it.

During this week I'll also add support for SvelteKit `data` exports. That might make this whole thing alot easier 👍🏻

**Comment by TorstenDittmann** [comment] 2023-10-01 13:01
I think that the issue is more of a Svelte Kit issue with the imports. Closing this for now.

**Closed by TorstenDittmann** 2023-10-01 13:01 UTC
